### ISSUE TITLE
Allow filtering on tag presence and tag absence

### ISSUE THREAD

**Issue by kalfa** [puppetlabs/puppetlabs-aws_inventory#16]
## Use Case
Filtering against AWS objects which have a specific tag present
Filtering against AWS objects which have a specific tag absent

alternatively, if it is already possible, to add it in the documentation / examples.

## Describe the Solution You Would Like

I cannot find any way to select a group of target against the presence of absence of certain tags.

It's quite common to have certain contextual tags, which automatically declare the instance to belong or not to a certain category/group or machine.

In other words adding the ability to express
- a filter rule which would pass when matching <ANY> value for a specified tag key (presence of tag)
```
groups:
  - name:  have_my_tag
    targets:
      - filters
         - name: tag:MyTag
            values: []
  - name:  have_not_my_tag
```

with an emtpy array, ultimately meaning all the specified values (i.e. empty set) are matching, so the rule is passing

- a filter rule which would pass when the object has no specified tag key (absence of tag)
```
groups:
  - name:  have_my_tag
     targets:
      - filters
         - name: tag:MyTag
```

no values key means it's absent.

of course, I don't mind the yaml way of expressing it, I don't mind any approach.

## Describe Alternatives You've Considered

There are no other ways to do it, or at least they are not ducumented / easy to find. 

My alternative is changing completely the way we tag objects, to allow aws_inventory to filter, which is not optimal and  is a point in favour to look outside bolt.

thanks!
